# ============================================================
# FastChat — AI Chatbot API built with FastAPI + Claude API
# ============================================================
# This file is the heart of the application. It defines all
# the API routes, connects to the Claude AI service, and
# manages per-session conversation history.
# ============================================================

# --- Imports ------------------------------------------------
# FastAPI is the web framework that handles HTTP requests
from fastapi import FastAPI, HTTPException

# StaticFiles lets us serve files from a folder (our HTML UI)
# FileResponse sends a specific file back to the browser
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse

# Uvicorn is the server that actually runs FastAPI
import uvicorn

# The official Anthropic Python SDK — used to call Claude
import anthropic

# os lets us read environment variables (like our API key)
import os

# datetime is used to generate a timestamp for the /health route
from datetime import datetime, timezone

# load_dotenv reads our .env file and puts values into os.environ
from dotenv import load_dotenv

# BaseModel is used to define the shape (schema) of request/response data
from pydantic import BaseModel

# --- Load environment variables ------------------------------
# This reads the .env file in the project root.
# After this call, os.getenv("ANTHROPIC_API_KEY") will return
# whatever value you put in your .env file.
load_dotenv()

# Fetch the API key from the environment
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

# If the key is missing or still the placeholder, raise an error
# immediately so the developer sees a helpful message right away
# instead of a confusing crash later.
if not ANTHROPIC_API_KEY or ANTHROPIC_API_KEY == "your_api_key_here":
    raise RuntimeError(
        "\n\n❌  ANTHROPIC_API_KEY is missing or not set!\n"
        "To fix this:\n"
        "  1. Copy .env.example to .env\n"
        "     Windows:  copy .env.example .env\n"
        "     Mac/Linux: cp .env.example .env\n"
        "  2. Open .env and replace 'your_api_key_here' with your real key\n"
        "     Get a key at: https://console.anthropic.com\n"
        "  3. Restart the server.\n"
    )

# --- Initialize the Anthropic client ------------------------
# This creates a client object we'll use to send messages to Claude.
# It automatically picks up ANTHROPIC_API_KEY from the environment.
client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

# --- Initialize the FastAPI application ---------------------
# title and description appear in the auto-generated API docs
# (visit http://localhost:8000/docs to see them)
app = FastAPI(
    title="FastChat API",
    description=(
        "A beginner-friendly chatbot API powered by FastAPI and the "
        "Anthropic Claude API. Supports multi-turn conversations with "
        "per-session history. Visit /ui for the browser chat interface."
    ),
    version="1.0.0",
)

# --- Mount the static files folder --------------------------
# This tells FastAPI: "any request to /static/... should serve
# the matching file from the ./static/ folder on disk."
# Our index.html lives at static/index.html.
app.mount("/static", StaticFiles(directory="static"), name="static")

# --- Conversation history store -----------------------------
# A plain Python dictionary that maps session_id → list of messages.
# Each message is a dict with "role" ("user" or "assistant") and "content".
# Example:
#   {
#     "abc123": [
#       {"role": "user",      "content": "Hello!"},
#       {"role": "assistant", "content": "Hi there! How can I help?"},
#     ]
#   }
#
# NOTE: This is an in-memory store — it resets when the server restarts.
# For a production app you'd use a database instead.
conversation_history: dict = {}

# --- Pydantic models ----------------------------------------
# Pydantic models define the exact shape of data we expect to
# receive (request body) or send back (response body).
# FastAPI uses these to automatically validate and document the API.

class ChatRequest(BaseModel):
    """Data the client must send when posting a message."""
    # The text message the user wants to send to Claude
    message: str
    # A unique ID that groups messages into a conversation.
    # Defaults to "default" so simple clients don't need to set it.
    session_id: str = "default"


class ChatResponse(BaseModel):
    """Data FastAPI sends back after getting Claude's reply."""
    # The text reply generated by Claude
    reply: str
    # Echo back the session_id so the client can track conversations
    session_id: str


# === ROUTES =================================================

# --- GET / --------------------------------------------------
# The root route. Returns a friendly JSON welcome message.
# Useful for quickly checking that the server is running.
@app.get("/")
def root():
    """Welcome endpoint — confirms the API is alive."""
    return {
        "api": "FastChat API",
        "status": "running",
        "message": (
            "Welcome to FastChat! Send a POST request to /chat "
            "to start a conversation, or open /ui for the browser interface."
        ),
        "docs": "/docs",
    }


# --- GET /health --------------------------------------------
# Health-check endpoint. Monitoring tools and load balancers
# often call this to confirm the service is healthy.
@app.get("/health")
def health_check():
    """Returns the current health status and a UTC timestamp."""
    return {
        "status": "ok",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "service": "FastChat API",
    }


# --- GET /ui ------------------------------------------------
# Returns the HTML file that provides the browser-based chat UI.
# FileResponse streams the file directly to the browser.
@app.get("/ui")
def chat_ui():
    """Serves the single-page chat interface."""
    return FileResponse("static/index.html")


# --- POST /chat ---------------------------------------------
# This is the main endpoint. The client sends a message and
# gets back a reply from Claude, with full conversation context.
@app.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    """
    Accepts a user message and session_id, calls the Claude API
    with the full conversation history, and returns the AI reply.
    """

    # Step 1: Retrieve (or create) the history for this session.
    # If this is the first message for this session_id, we start
    # with an empty list. setdefault does both checks in one call.
    history = conversation_history.setdefault(request.session_id, [])

    # Step 2: Add the user's new message to the history.
    # Claude expects messages in this exact format.
    history.append({
        "role": "user",
        "content": request.message,
    })

    # Step 3: Call the Claude API inside a try/except block.
    # We catch specific Anthropic errors so we can return clear
    # error messages instead of a generic 500 crash.
    try:
        # messages.create() sends the full conversation to Claude.
        # - model: which Claude model to use
        # - system: a hidden instruction that sets Claude's personality
        # - messages: the full back-and-forth history for this session
        # - max_tokens: the maximum length of Claude's reply
        response = client.messages.create(
            model="claude-sonnet-4-5",
            system=(
                "You are a friendly assistant helping beginners learn "
                "FastAPI and Python. Keep answers clear and encouraging."
            ),
            messages=history,
            max_tokens=1024,
        )

        # Extract the text from the first content block in the response
        assistant_reply = response.content[0].text

    except anthropic.AuthenticationError:
        # Raised when the API key is invalid or expired
        raise HTTPException(
            status_code=401,
            detail={
                "error": "Authentication failed",
                "error_message": (
                    "Your ANTHROPIC_API_KEY is invalid or has expired. "
                    "Check your .env file and make sure the key is correct. "
                    "Get a new key at https://console.anthropic.com"
                ),
            },
        )

    except anthropic.APIConnectionError:
        # Raised when there's a network problem reaching Anthropic's servers
        raise HTTPException(
            status_code=503,
            detail={
                "error": "Connection error",
                "error_message": (
                    "Could not connect to the Anthropic API. "
                    "Check your internet connection and try again."
                ),
            },
        )

    except anthropic.RateLimitError:
        # Raised when you've sent too many requests in a short time
        raise HTTPException(
            status_code=429,
            detail={
                "error": "Rate limit exceeded",
                "error_message": (
                    "You've sent too many requests too quickly. "
                    "Wait a moment and try again. If this keeps happening, "
                    "check your Anthropic usage limits at https://console.anthropic.com"
                ),
            },
        )

    except Exception as e:
        # Catch-all for any other unexpected errors
        raise HTTPException(
            status_code=500,
            detail={
                "error": "Unexpected server error",
                "error_message": (
                    f"Something went wrong on the server: {str(e)}. "
                    "Check the server logs for more details."
                ),
            },
        )

    # Step 4: Save Claude's reply to the history so future messages
    # in this session include the full context.
    history.append({
        "role": "assistant",
        "content": assistant_reply,
    })

    # Step 5: Return the structured response
    return ChatResponse(reply=assistant_reply, session_id=request.session_id)


# --- Run the app directly (optional) ------------------------
# This block lets you run the app with: python main.py
# For development, prefer: uvicorn main:app --reload
if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
